name: dartz
version: 0.10.1-dart3
homepage: https://github.com/spebbe/dartz
description: Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ">=1.17.1"
